name: Sourcegraph
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lsif:
    runs-on: ubuntu-latest
    name: "Upload LSIF"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1.1.2
        with:
          jvm: adopt:8
          apps: lsif-java
      - run: lsif-java index
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          endpoint: https://sourcegraph.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: dump.lsif
